import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
// import localFont from "next/font/local";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// If loading a variable font, you don't need to specify the font weight
const vazirmatn = Vazirmatn({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "hosein jalali",
  description: "Generated by hosein jalali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirmatn.className} antialiased`}>
        <div className="max-w-7xl mx-auto min-h-dvh">
          {children}
        </div>
      </body>
    </html>
  );
}
